data_ingestion:
  test_size: 0.3

data_transformation:
  oov_token: '<OOV>'
  padding_type: 'post'
  trunc_type: 'post'
  vocab_size: 1000
  max_text_length: 171

model_training:
  vocab_size: 1000
  embedding_dim: 16
  loss: 'binary_crossentropy'
  optimizer: 'adam'
  learning_rate: 0.001
  metrics: ['accuracy']
  num_epochs: 30
  max_text_length: 171